development:
  adapter: postgresql
  username: postgres
  password: pwd
  database: photoalbum_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  username: postgres
  password: pwd
  database: photoalbum_test
  host: localhost
  pool: 5
